name: HowToWorkWith-test
on: [push]
jobs:
  HowToWorkWith-test:
    runs-on: ubuntu-20.04
    steps:
      - run:
          echo *** LOAD ***
          sudo mkdir -p /home/sku_study/
          sudo git clone https::github.com/jeongdonggi/Sku_Study.git /home/sku_study/
          cd /home/sku_study/
          echo *** LOAD **
          
          echo *** INSTALL ***
          sudo apt-get update
          sudo apt install python3-pip
          
          sudo apt install python3-pytest
          
          echo *** INSTALL ***
          
          echo *** TEST ***
          pytest-3 test_op.py --disable-warnings
          echo *** TEST ***
